export default {
    SWITCH_COLOR_THEME_BEGIN: 'SWITCH_COLOR_THEME_BEGIN',
    SWITCH_COLOR_THEME_SUCCESS: 'SWITCH_COLOR_THEME_SUCCESS',
    SWITCH_COLOR_THEME_FAILURE: 'SWITCH_COLOR_THEME_FAILURE',
    CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE'
}